((file "File"
       (new-file "Visit New File..." :help "Specify a new file's name, to edit the file")
       (open-file "Open File..." :help "Read an existing file into an Emacs buffer")
       (dired "Open Directory..." :help "Read a directory, to operate on its files")
       (insert-file "Insert File..." :help "Insert another file into current buffer")
       (kill-buffer "Close" :help "Discard (kill) current buffer")
       (save-buffer "Save" :help "Save current buffer to its file")
       (write-file "Save As..." :help "Write current buffer to another file")
       (revert-buffer "Revert Buffer" :help "Re-read current buffer from its file")
       (recover-session "Recover Crashed Session" :help "Recover edits from a crashed session")
       (print-buffer "Print Buffer" :help "Print current buffer with page headings")
       (print-region "Print Region" :help "Print region between mark and current position")
       (ps-print-buffer-faces "Postscript Print Buffer" :help "Pretty-print current buffer to PostScript printer")
       (ps-print-region-faces "Postscript Print Region" :help "Pretty-print marked region to PostScript printer")
       (ps-print-buffer "Postscript Print Buffer (B+W)" :help "Pretty-print current buffer in black and white to PostScript printer")
       (ps-print-region "Postscript Print Region (B+W)" :help "Pretty-print marked region in black and white to PostScript printer")
       (split-window "Split Window" :help "Split selected window in two windows")
       (one-window "Remove Splits" :help "Selected window grows to fill the whole frame")
       (make-frame "New Frame" :help "Open a new frame")
       (make-frame-on-display "New Frame on Display..." :help "Open a new frame on another display")
       (delete-this-frame "Delete Frame" :help "Delete currently selected frame")
       (exit-emacs "Exit Emacs" :help "Save unsaved buffers, then exit"))
 (edit "Edit"
       (undo "Undo" :help "Undo last operation")
       (cut "Cut")
       (copy "Copy")
       (paste "Paste" :help "Paste (yank) text most recently cut/copied")
       (select-paste "Select and Paste")
       (clear "Clear" :help "Delete the text in region between mark and current position")
       (mark-whole-buffer "Select All" :help "Mark the whole buffer for a subsequent cut/copy.")
       (search "Search"
	       (search-forward "String Forward..." :help "Search forward for a string")
	       (search-backward "String Backwards..." :help "Search backwards for a string")
	       (re-search-forward "Regexp Forward..." :help "Search forward for a regular expression")
	       (re-search-backward "Regexp Backwards..." :help "Search backwards for a regular expression")
	       (repeat-search-fwd "Repeat Forward" :help "Repeat last search forward")
	       (repeat-search-back "Repeat Backwards" :help "Repeat last search backwards")
	       (tags-srch "Search tagged files..." :help "Search for a regexp in all tagged files")
	       (tags-continue "Continue Tags Search" :help "Continue last tags search operation")
	       (i-search "Incremental Search"
			 (isearch-forward "Forward String..." :help "Search forward for a string as you type it")
			 (isearch-backward "Backward String..." :help "Search backwards for a string as you type it")
			 (isearch-forward-regexp "Forward Regexp..." :help "Search forward for a regular expression as you type it")
			 (isearch-backward-regexp "Backward Regexp..." :help "Search backwards for a regular expression as you type it")))
       (replace "Replace"
		(query-replace "Replace String..." :help "Replace string interactively, ask about each occurrence")
		(query-replace-regexp "Replace Regexp..." :help "Replace regular expression interactively, ask about each occurrence")
		(tags-repl "Replace in tagged files..." :help "Interactively replace a regexp in all tagged files")
		(tags-repl-continue "Continue Replace" :help "Continue last tags replace operation"))
       (goto "Go To"
	     (go-to-line "Goto Line..." :help "Read a line number and go to that line")
	     (go-to-pos "Goto Buffer Position..." :help "Read a number N and go to buffer position N")
	     (beg-of-buf "Goto Beginning of Buffer")
	     (end-of-buf "Goto End of Buffer")
	     (find-tag "Find Tag..." :help "Find definition of function or variable")
	     (find-tag-otherw "Find Tag in Other Window..." :help "Find function/variable definition in another window")
	     (next-tag "Find Next Tag" :help "Find next function/variable matching last tag name")
	     (next-tag-otherw "Next Tag in Other Window" :help "Find next function/variable matching last tag name in another window")
	     (apropos-tags "Tags Apropos..." :help "Find function/variables whose names match regexp")
	     (set-tags-name "Set Tags File Name..." :help "Tell Tags commands which tag table file to use"))
       (bookmark "Bookmarks"
		 (jump "Jump to Bookmark...")
		 (set "Set Bookmark...")
		 (insert "Insert Contents...")
		 (locate "Insert Location...")
		 (rename "Rename Bookmark...")
		 (delete "Delete Bookmark...")
		 (edit "Edit Bookmark List")
		 (save "Save Bookmarks")
		 (write "Save Bookmarks As...")
		 (load "Load a Bookmark File..."))
       (fill "Fill" :help "Fill text in region to fit between left and right margin")
       (props "Text Properties"
	      (fc "Face"
		  (100 "default")
		  (98 "bold")
		  (105 "italic")
		  (108 "bold-italic")
		  (117 "underline")
		  (111 "Other..."))
	      (fg "Foreground Color"
		  (111 "Other..."))
	      (bg "Background Color"
		  (111 "Other..."))
	      (sp "Special Properties"
		  (114 "Read-Only")
		  (118 "Invisible")
		  (116 "Intangible")
		  (115 "Remove Special"))
	      (ju "Justification"
		  (117 "Unfilled")
		  (108 "Left")
		  (114 "Right")
		  (98 "Full")
		  (99 "Center"))
	      (in "Indentation"
		  (increase-left-margin "Indent More")
		  (decrease-left-margin "Indent Less")
		  (increase-right-margin "Indent Right More")
		  (decrease-right-margin "Indent Right Less"))
	      (rm "Remove Face Properties")
	      (ra "Remove Text Properties")
	      (dp "Describe Properties")
	      (df "Display Faces")
	      (dc "Display Colors")))
 (options "Options"
	  (transient-mark-mode "Active Region Highlighting" :help "Make text in active region stand out in color (Transient Mark mode)")
	  (highlight-paren-mode "Paren Match Highlighting" :help "Highlight matching/mismatched parentheses at cursor (Show Paren mode)")
	  (truncate-lines "Truncate Long Lines in this Buffer" :help "Truncate long lines on the screen")
	  (auto-fill-mode "Word Wrap in Text Modes" :help "Automatically fill text between left and right margins (Auto Fill)")
	  (case-fold-search "Case-Insensitive Search" :help "Ignore letter-case in search")
	  (cua-emulation-mode "Shift movement mark region (CUA)" :help "Use shifted movement keys to set and extend the region.")
	  (cua-mode "C-x/C-c/C-v Cut and Paste (CUA)" :help "Use C-z/C-x/C-c/C-v keys for undo/cut/copy/paste")
	  (uniquify "Use Directory Names in Buffer Names" :help "Uniquify buffer names by adding parent directory names")
	  (save-place "Save Place in Files between Sessions" :help "Visit files of previous session when restarting Emacs")
	  (blink-cursor-mode "Blinking Cursor" :help "Whether the cursor blinks (Blink Cursor mode)")
	  (debug-on-error "Enter Debugger on Error" :help "Enter Lisp debugger when an error is signaled")
	  (debug-on-quit "Enter Debugger on Quit/C-g" :help "Enter Lisp debugger when C-g is pressed")
	  (mule "Mule (Multilingual Environment)"
		(set-language-environment "Set Language Environment"
					  (Default "Default")
					  (Chinese "Chinese"
						   (Chinese-GB "Chinese-GB")
						   (Chinese-BIG5 "Chinese-BIG5")
						   (Chinese-CNS "Chinese-CNS")
						   (Chinese-EUC-TW "Chinese-EUC-TW")
						   (Chinese-GBK "Chinese-GBK"))
					  (Cyrillic "Cyrillic"
						    (Cyrillic-ISO "Cyrillic-ISO")
						    (Cyrillic-KOI8 "Cyrillic-KOI8")
						    (Russian "Russian")
						    (Ukrainian "Ukrainian")
						    (Cyrillic-ALT "Cyrillic-ALT")
						    (Tajik "Tajik")
						    (Bulgarian "Bulgarian")
						    (Belarusian "Belarusian"))
					  (Indian "Indian"
						  (Devanagari "Devanagari")
						  (Malayalam "Malayalam")
						  (Tamil "Tamil")
						  (Kannada "Kannada"))
					  (English "English")
					  (ASCII "ASCII")
					  (Ethiopic "Ethiopic")
					  (European "European"
						    (Latin-1 "Latin-1")
						    (Latin-2 "Latin-2")
						    (Latin-3 "Latin-3")
						    (Latin-4 "Latin-4")
						    (Latin-5 "Latin-5")
						    (Latin-8 "Latin-8")
						    (Latin-9 "Latin-9")
						    (Dutch "Dutch")
						    (German "German")
						    (French "French")
						    (Italian "Italian")
						    (Slovenian "Slovenian")
						    (Spanish "Spanish")
						    (Polish "Polish")
						    (Welsh "Welsh")
						    (Latin-6 "Latin-6")
						    (Latin-7 "Latin-7")
						    (Lithuanian "Lithuanian")
						    (Latvian "Latvian")
						    (Swedish "Swedish")
						    (Croatian "Croatian")
						    (Brazilian\ Portuguese "Brazilian Portuguese")
						    (Czech "Czech")
						    (Slovak "Slovak")
						    (Romanian "Romanian")
						    (Georgian "Georgian"))
					  (Turkish "Turkish")
					  (Greek "Greek")
					  (Hebrew "Hebrew")
					  (Windows-1255 "Windows-1255")
					  (Japanese "Japanese")
					  (Korean "Korean")
					  (Lao "Lao")
					  (Thai "Thai")
					  (Tibetan "Tibetan")
					  (Vietnamese "Vietnamese")
					  (IPA "IPA")
					  (UTF-8 "UTF-8"))
		(toggle-input-method "Toggle Input Method")
		(set-input-method "Select Input Method...")
		(set-various-coding-system "Set Coding Systems"
					   (universal-coding-system-argument "For Next Command" :help "Coding system to be used by next command")
					   (set-buffer-file-coding-system "For Saving This Buffer" :help "How to encode this buffer when saved")
					   (revert-buffer-with-coding-system "For Reverting This File Now" :help "Revisit this file immediately using specified coding system")
					   (set-file-name-coding-system "For File Name" :help "How to decode/encode file names")
					   (set-keyboard-coding-system "For Keyboard" :help "How to decode keyboard input")
					   (set-terminal-coding-system "For Terminal" :help "How to encode terminal output")
					   (set-selection-coding-system "For X Selections/Clipboard" :help "How to en/decode data to/from selection/clipboard")
					   (set-next-selection-coding-system "For Next X Selection" :help "How to en/decode next selection/clipboard operation")
					   (set-buffer-process-coding-system "For I/O with Subprocess" :help "How to en/decode I/O from/to subprocess connected to this buffer"))
		(view-hello-file "Show Multi-lingual Text" :help "Display file which says HELLO in many languages")
		(describe-language-environment "Describe Language Environment"
					       (Default "Default")
					       (Chinese "Chinese"
							(Chinese-GB "Chinese-GB")
							(Chinese-BIG5 "Chinese-BIG5")
							(Chinese-CNS "Chinese-CNS")
							(Chinese-EUC-TW "Chinese-EUC-TW")
							(Chinese-GBK "Chinese-GBK"))
					       (Cyrillic "Cyrillic"
							 (Cyrillic-ISO "Cyrillic-ISO")
							 (Cyrillic-KOI8 "Cyrillic-KOI8")
							 (Russian "Russian")
							 (Ukrainian "Ukrainian")
							 (Cyrillic-ALT "Cyrillic-ALT")
							 (Tajik "Tajik")
							 (Bulgarian "Bulgarian")
							 (Belarusian "Belarusian"))
					       (Indian "Indian"
						       (Devanagari "Devanagari")
						       (Malayalam "Malayalam")
						       (Tamil "Tamil")
						       (Kannada "Kannada"))
					       (English "English")
					       (ASCII "ASCII")
					       (Ethiopic "Ethiopic")
					       (European "European"
							 (Latin-1 "Latin-1")
							 (Latin-2 "Latin-2")
							 (Latin-3 "Latin-3")
							 (Latin-4 "Latin-4")
							 (Latin-5 "Latin-5")
							 (Latin-8 "Latin-8")
							 (Latin-9 "Latin-9")
							 (Dutch "Dutch")
							 (German "German")
							 (French "French")
							 (Italian "Italian")
							 (Slovenian "Slovenian")
							 (Spanish "Spanish")
							 (Polish "Polish")
							 (Welsh "Welsh")
							 (Latin-6 "Latin-6")
							 (Latin-7 "Latin-7")
							 (Lithuanian "Lithuanian")
							 (Latvian "Latvian")
							 (Swedish "Swedish")
							 (Croatian "Croatian")
							 (Brazilian\ Portuguese "Brazilian Portuguese")
							 (Czech "Czech")
							 (Slovak "Slovak")
							 (Romanian "Romanian")
							 (Georgian "Georgian"))
					       (Turkish "Turkish")
					       (Greek "Greek")
					       (Hebrew "Hebrew")
					       (Windows-1255 "Windows-1255")
					       (Japanese "Japanese")
					       (Korean "Korean")
					       (Lao "Lao")
					       (Thai "Thai")
					       (Tibetan "Tibetan")
					       (Vietnamese "Vietnamese")
					       (IPA "IPA")
					       (UTF-8 "UTF-8"))
		(describe-input-method "Describe Input Method..." :help "Keyboard layout for a specific input method")
		(describe-coding-system "Describe Coding System...")
		(list-character-sets "List Character Sets" :help "Show table of available character sets")
		(mule-diag "Show All of Mule Status" :help "Display multilingual environment settings")
		(set-menu-language "Set Menu Language"))
	  (showhide "Show/Hide"
		    (showhide-tool-bar "Tool-bar" :help "Turn tool-bar on/off")
		    (menu-bar-mode "Menu-bar" :help "Toggle menu-bar on/off")
		    (showhide-tooltip-mode "Tooltips" :help "Toggle tooltips on/off")
		    (showhide-scroll-bar "Scroll-bar"
					 (none "None" :help "Turn off scroll-bar")
					 (left "On the Left" :help "Scroll-bar on the left side")
					 (right "On the Right" :help "Scroll-bar on the right side"))
		    (showhide-fringe "Fringe"
				     (none "None" :help "Turn off fringe")
				     (left "On the Left" :help "Fringe only on the left side")
				     (right "On the Right" :help "Fringe only on the right side")
				     (default "Default" :help "Default width fringe on both left and right side")
				     (customize "Customize Fringe" :help "Detailed customization of fringe")
				     (indicate-empty-lines "Empty Line Indicators" :help "Indicate trailing empty lines in fringe")
				     (showhide-fringe-ind "Buffer Boundaries"
							  (none "No Indicators" :help "Hide all buffer boundary indicators and arrows")
							  (left "In Left Fringe" :help "Show buffer boundaries and arrows in left fringe")
							  (right "In Right Fringe" :help "Show buffer boundaries and arrows in right fringe")
							  (box "Opposite, No Arrows" :help "Show top/bottom indicators in opposite fringes, no arrows")
							  (mixed "Opposite, Arrows Right" :help "Show top/bottom indicators in opposite fringes, arrows in right")
							  (customize "Other (Customize)" :help "Additional choices available through Custom buffer")))
		    (showhide-speedbar "Speedbar" :help "Display a Speedbar quick-navigation frame")
		    (showhide-date-time "Time, Load and Mail" :help "Display time, system load averages and mail status in mode line")
		    (showhide-battery "Battery Status" :help "Display battery status information in mode line")
		    (size-indication-mode "Size Indication" :help "Show the size of the buffer in the mode line")
		    (line-number-mode "Line Numbers" :help "Show the current line number in the mode line")
		    (column-number-mode "Column Numbers" :help "Show the current column number in the mode line"))
	  (mouse-set-font "Set Font/Fontset..." :help "Select a font from list of known fonts/fontsets")
	  (save "Save Options" :help "Save options set from the menu above")
	  (customize "Customize Emacs"
		     (customize "Top-level Customization Group" :help "The master group called `Emacs'")
		     (customize-browse "Browse Customization Groups" :help "Browse all customization groups")
		     (customize-saved "Saved Options" :help "Customize previously saved options")
		     (customize-changed-options "New Options..." :help "Options added or changed in recent Emacs versions")
		     (customize-option "Specific Option..." :help "Customize value of specific option")
		     (customize-face "Specific Face..." :help "Customize attributes of specific face")
		     (customize-group "Specific Group..." :help "Customize settings of specific group")
		     (customize-apropos "Settings Matching Regexp..." :help "Browse customizable settings whose names match regexp")
		     (customize-apropos-options "Options Matching Regexp..." :help "Browse options whose names match regexp")
		     (customize-apropos-faces "Faces Matching Regexp..." :help "Browse faces whose names match regexp")
		     (customize-apropos-groups "Groups Matching Regexp..." :help "Browse groups whose names match regexp")))
 (buffer "Buffers"
	 ("*scratch*" "*scratch*  *")
	 ("*Messages*" "*Messages*  *")
	 (next-buffer "Next Buffer" :help "Switch to the \"next\" buffer in a cyclic order")
	 (previous-buffer "Previous Buffer" :help "Switch to the \"previous\" buffer in a cyclic order")
	 (select-named-buffer "Select Named Buffer..." :help "Prompt for a buffer name, and select that buffer in the current window")
	 (list-all-buffers "List All Buffers" :help "Pop up a window listing all Emacs buffers"))
 (tools "Tools"
	(grep "Search Files (with grep)..." :help "Search files for strings or regexps (with grep)")
	(compile "Compile..." :help "Invoke compiler or Make, view compilation errors")
	(shell "Shell Command..." :help "Invoke a shell command and catch its output")
	(shell-on-region "Shell Command on Region..." :help "Pass marked region to a shell command")
	(gdb "Debugger (GDB)..." :help "Debug a program from within Emacs with GDB")
	(spell "Spell Checking"
	       (ispell-buffer "Spell-Check Buffer" :help "Check spelling of selected buffer")
	       (ispell-message "Spell-Check Message" :help "Skip headers and included message text")
	       (ispell-region "Spell-Check Region" :help "Spell-check text in marked region")
	       (ispell-comments-and-strings "Spell-Check Comments" :help "Spell-check only comments and strings")
	       (ispell-word "Spell-Check Word" :help "Spell-check word at cursor")
	       (ispell-continue "Continue Spell-Checking" :help "Continue spell checking last region")
	       (ispell-complete-word-interior-frag "Complete Word Fragment" :help "Complete word fragment at cursor")
	       (ispell-complete-word "Complete Word" :help "Complete word at cursor using dictionary")
	       (flyspell-mode "Automatic spell checking (Flyspell)" :help "Check spelling while you edit the text")
	       (ispell-help "Help" :help "Show standard Ispell keybindings and commands")
	       (ispell-customize "Customize..." :help "Customize spell checking options")
	       (ispell-pdict-save "Save Dictionary" :help "Save personal dictionary")
	       (ispell-kill-ispell "Kill Process" :help "Terminate Ispell subprocess")
	       (ispell-change-dictionary "Change Dictionary..." :help "Supply explicit dictionary file name"))
	(compare "Compare (Ediff)"
		 (ediff-files "Two Files...")
		 (ediff-buffers "Two Buffers...")
		 (ediff-files3 "Three Files...")
		 (ediff-buffers3 "Three Buffers...")
		 (ediff-directories "Two Directories...")
		 (ediff-directories3 "Three Directories...")
		 (ediff-revision "File with Revision...")
		 (ediff-dir-revision "Directory Revisions...")
		 (ediff-regions-wordwise "Regions Word-by-word...")
		 (ediff-regions-linewise "Regions Line-by-line...")
		 (ediff-windows-wordwise "Windows Word-by-word...")
		 (ediff-windows-linewise "Windows Line-by-line...")
		 (window "This Window and Next Window"))
	(ediff-merge "Merge"
		     (ediff-merge-files "Files...")
		     (ediff-merge-files-with-ancestor "Files with Ancestor...")
		     (ediff-merge-buffers "Buffers...")
		     (ediff-merge-buffers-with-ancestor "Buffers with Ancestor...")
		     (ediff-merge-directories "Directories...")
		     (ediff-merge-directories-with-ancestor "Directories with Ancestor...")
		     (ediff-merge-revisions "Revisions...")
		     (ediff-merge-revisions-with-ancestor "Revisions with Ancestor...")
		     (ediff-merge-dir-revisions "Directory Revisions...")
		     (ediff-merge-dir-revisions-with-ancestor "Directory Revisions with Ancestor..."))
	(epatch "Apply Patch"
		(ediff-patch-file "To a File...")
		(ediff-patch-buffer "To a Buffer..."))
	(ediff-misc "Ediff Miscellanea"
		    (ediff-doc "Ediff Manual")
		    (ediff-cust "Customize Ediff")
		    (eregistry "List Ediff Sessions")
		    (emultiframe "Toggle use of separate control buffer frame"))
	(vc "Version Control"
	    (vc-register "Register")
	    (vc-next-action "Check In/Out")
	    (vc-update "Update to Latest Version")
	    (vc-revert-buffer "Revert to Base Version")
	    (undo "Undo Last Check-In")
	    (vc-insert-header "Insert Header")
	    (vc-print-log "Show History")
	    (vc-update-change-log "Update ChangeLog")
	    (vc-diff "Compare with Base Version")
	    (vc-version-other-window "Show Other Version")
	    (vc-rename-file "Rename File")
	    (vc-annotate "Annotate")
	    (vc-directory "VC Directory Listing")
	    (vc-create-snapshot "Create Snapshot")
	    (vc-retrieve-snapshot "Retrieve Snapshot"))
	(pcl-cvs "PCL-CVS"
		 (examine "Examine Directory" :help "Examine the current state of a workarea")
		 (update "Update Directory" :help "Fetch updates from the repository")
		 (checkout "Checkout Module" :help "Check out a module from the repository")
		 (status "Directory Status" :help "A more verbose status of a workarea"))
	(gnus "Read Net News (Gnus)" :help "Read network news groups")
	(rmail
	 (format "Read Mail (with %s)"
		 (read-mail-item-name))
	 :help "Read your mail and reply to it")
	(compose-mail
	 (format "Send Mail (with %s)"
		 (send-mail-item-name))
	 :help "Send a mail message")
	(directory-search "Directory Search"
			  (load "Load Hotlist of Servers")
			  (new "New Server")
			  (query "Query with Form")
			  (expand-inline "Expand Inline Query")
			  (email "Get Email")
			  (phone "Get Phone"))
	(calendar "Calendar")
	(calc "Programmable Calculator" :help "Invoke the Emacs built-in full scientific calculator")
	(simple-calculator "Simple Calculator" :help "Invoke the Emacs built-in quick calculator")
	(games "Games"
	       (5x5 "5x5" :help "Fill in all the squares on a 5x5 board")
	       (adventure "Adventure" :help "Dunnet, a text Adventure game for Emacs")
	       (black-box "Blackbox" :help "Find balls in a black box by shooting rays")
	       (gomoku "Gomoku" :help "Mark 5 contiguous squares (like tic-tac-toe)")
	       (hanoi "Towers of Hanoi" :help "Watch Towers-of-Hanoi puzzle solved by Emacs")
	       (life "Life" :help "Watch how John Conway's cellular automaton evolves")
	       (mult "Multiplication Puzzle" :help "Exercise brain with multiplication")
	       (snake "Snake" :help "Move snake around avoiding collisions")
	       (solitaire "Solitaire")
	       (tetris "Tetris")
	       (zone "Zone Out" :help "Play tricks with Emacs display when Emacs is idle")))
 (help-menu "Help"
	    (emacs-tutorial "Emacs Tutorial" :help "Learn how to use Emacs")
	    (emacs-tutorial-language-specific "Emacs Tutorial (choose language)..." :help "Learn how to use Emacs (choose a language)")
	    (emacs-faq "Emacs FAQ")
	    (emacs-news "Emacs News" :help "New features of this version")
	    (emacs-problems "Emacs Known Problems")
	    (report-emacs-bug "Send Bug Report..." :help "Send e-mail to Emacs maintainers")
	    (apropos "Search Documentation"
		     (emacs-glossary "Emacs Terminology" :help "Display the Glossary section of the Emacs manual")
		     (emacs-index-search "Look Up Subject in User Manual..." :help "Find description of a subject in Emacs User manual")
		     (elisp-index-search "Look Up Subject in ELisp Manual..." :help "Find description of a subject in Emacs Lisp manual")
		     (emacs-key-command-node "Look Up Key in User Manual..." :help "Display manual section that describes a key")
		     (emacs-command-node "Look Up Command in User Manual..." :help "Display manual section that describes a command")
		     (apropos-commands "Find Commands by Name..." :help "Find commands whose names match a regexp")
		     (apropos-variables "Find Options by Name..." :help "Find variables whose names match a regexp")
		     (apropos-value "Find Options by Value..." :help "Find variables whose values match a regexp")
		     (apropos "Find Any Object by Name..." :help "Find symbols of any kind whose names match a regexp")
		     (apropos-documentation "Search Documentation Strings..." :help "Find functions and variables whose doc strings match a regexp"))
	    (describe "Describe"
		      (describe-mode "Describe Buffer Modes" :help "Describe this buffer's major and minor mode")
		      (describe-key-1 "Describe Key or Mouse Operation..." :help "Display documentation of command bound to a key, a click, or a menu-item")
		      (describe-function "Describe Function..." :help "Display documentation of function/command")
		      (describe-variable "Describe Variable..." :help "Display documentation of variable/option")
		      (describe-face "Describe Face..." :help "Display the properties of a face")
		      (describe-current-display-table "Describe Display Table" :help "Describe the current display table")
		      (list-keybindings "List Key Bindings" :help "Display all current keybindings (keyboard shortcuts)")
		      (describe-language-environment "Describe Language Environment"
						     (Default "Default")
						     (Chinese "Chinese"
							      (Chinese-GB "Chinese-GB")
							      (Chinese-BIG5 "Chinese-BIG5")
							      (Chinese-CNS "Chinese-CNS")
							      (Chinese-EUC-TW "Chinese-EUC-TW")
							      (Chinese-GBK "Chinese-GBK"))
						     (Cyrillic "Cyrillic"
							       (Cyrillic-ISO "Cyrillic-ISO")
							       (Cyrillic-KOI8 "Cyrillic-KOI8")
							       (Russian "Russian")
							       (Ukrainian "Ukrainian")
							       (Cyrillic-ALT "Cyrillic-ALT")
							       (Tajik "Tajik")
							       (Bulgarian "Bulgarian")
							       (Belarusian "Belarusian"))
						     (Indian "Indian"
							     (Devanagari "Devanagari")
							     (Malayalam "Malayalam")
							     (Tamil "Tamil")
							     (Kannada "Kannada"))
						     (English "English")
						     (ASCII "ASCII")
						     (Ethiopic "Ethiopic")
						     (European "European"
							       (Latin-1 "Latin-1")
							       (Latin-2 "Latin-2")
							       (Latin-3 "Latin-3")
							       (Latin-4 "Latin-4")
							       (Latin-5 "Latin-5")
							       (Latin-8 "Latin-8")
							       (Latin-9 "Latin-9")
							       (Dutch "Dutch")
							       (German "German")
							       (French "French")
							       (Italian "Italian")
							       (Slovenian "Slovenian")
							       (Spanish "Spanish")
							       (Polish "Polish")
							       (Welsh "Welsh")
							       (Latin-6 "Latin-6")
							       (Latin-7 "Latin-7")
							       (Lithuanian "Lithuanian")
							       (Latvian "Latvian")
							       (Swedish "Swedish")
							       (Croatian "Croatian")
							       (Brazilian\ Portuguese "Brazilian Portuguese")
							       (Czech "Czech")
							       (Slovak "Slovak")
							       (Romanian "Romanian")
							       (Georgian "Georgian"))
						     (Turkish "Turkish")
						     (Greek "Greek")
						     (Hebrew "Hebrew")
						     (Windows-1255 "Windows-1255")
						     (Japanese "Japanese")
						     (Korean "Korean")
						     (Lao "Lao")
						     (Thai "Thai")
						     (Tibetan "Tibetan")
						     (Vietnamese "Vietnamese")
						     (IPA "IPA")
						     (UTF-8 "UTF-8"))
		      (describe-input-method "Describe Input Method..." :help "Keyboard layout for specific input method")
		      (describe-coding-system "Describe Coding System...")
		      (describe-coding-system-briefly "Describe Coding System (Briefly)...")
		      (mule-diag "Show All of Mule Status" :help "Display multilingual environment settings"))
	    (emacs-manual "Read the Emacs Manual" :help "Full documentation of Emacs features")
	    (manuals "More Manuals"
		     (info-elintro "Introduction to Emacs Lisp" :help "Read the Introduction to Emacs Lisp Programming")
		     (info-elisp "Emacs Lisp Reference" :help "Read the Emacs Lisp Reference manual")
		     (info "All Other Manuals (Info)" :help "Read any of the installed manuals")
		     (info-apropos "Lookup Subject in all manuals..." :help "Find description of a subject in all installed manuals")
		     (order-emacs-manuals "Ordering Manuals" :help "How to order manuals from the Free Software Foundation")
		     (man "Read Man Page..." :help "Man-page docs for external commands and libraries"))
	    (finder-by-keyword "Find Emacs Packages" :help "Find packages and features by keyword")
	    (about "About Emacs" :help "Display version number, copyright info, and basic help")
	    (more "External Packages" :help "Lisp packages distributed separately for use in Emacs")
	    (describe-distribution "Getting New Versions" :help "How to get latest versions of Emacs")
	    (describe-copying "Copying Conditions" :help "Show the Emacs license (GPL)")
	    (describe-no-warranty "(Non)Warranty" :help "Explain that Emacs has NO WARRANTY")
	    (eliza "Emacs Psychotherapist" :help "Our doctor will help you feel better")))
